
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='sqredirect',
    version='1.2.0',
    python_requires='<4.0,>=2.7',
    author='spumer',
    author_email='spumer-tm@yandex.ru',
    entry_points={"console_scripts": ["sqredirect = sqredirect.redirect:sqredirect"]},
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['py2-ipaddress==3.*,>=3.4.2; python_version == "2.*" and python_version >= "2.7.0"', 'pyroute2>=0.4'],
    extras_require={"dev": ["dephell==0.*,>=0.8.3; python_version >= \"3.6\"", "pytest==6.*,>=6.2.2; python_version == \"3.*\" and python_version >= \"3.0.0\""]},
)
